Repository nhsx/standards-registry, pull requests merged in 2022-05, with the labels that each got.

#126 [STAN-514] spreadsheet importer updates
  .github/workflows/deploy-test.yml
  reader/.eslintrc.cjs
  reader/index.js
  reader/lib/parse/index.js
  reader/lib/parse/read.js
  reader/lib/write.js
  reader/lib/write/index.js
  reader/package-lock.json
  reader/package.json
  ui/cypress/fixtures/example.json
  ui/cypress/integration/standards/list.js
  ui/cypress/plugins/index.js
  ui/cypress/videos/home.js.mp4
  ui/cypress/videos/standards/list.js.mp4
  ui/cypress/videos/standards/standard-page.js.mp4
  ui/helpers/api.js
Labels: enhancement

#132 pass `--include-optional` flag in dockerfile
  ui/Dockerfile
Labels: dev-ops

#135 [STAN-547] AND filters
  .github/workflows/build-and-test.yml
  ui/components/Dataset/index.js
  ui/components/Expander/Expander.module.scss
  ui/components/Expander/index.js
  ui/components/FilterSummary/FilterSummary.module.scss
  ui/components/FilterSummary/index.js
  ui/components/Filters/Filters.module.scss
  ui/components/Filters/index.js
  ui/components/OptionSelect/styles.module.scss
  ui/components/Pagination/index.js
  ui/components/Search/index.js
  ui/components/Select/index.js
  ui/components/index.js
  ui/context/query.js
  ui/cypress/.eslintrc.js
  ui/cypress/.gitignore
  ui/cypress/integration/standards/list.js
  ui/cypress/videos/home.js.mp4
  ui/cypress/videos/standards/list.js.mp4
  ui/cypress/videos/standards/standard-page.js.mp4
  ui/helpers/api.js
  ui/package-lock.json
  ui/package.json
  ui/pages/api/refresh-list.js
  ui/pages/index.js
  ui/pages/search-results.js
  ui/pages/standards/index.js
Labels: ui changes

#144 update tag colour map
  ui/components/Tag/index.js
Labels: ui changes

#145 [STAN-557] Search and Filter fixes
  ui/components/Expander/Expander.module.scss
  ui/components/FilterSummary/index.js
  ui/components/Filters/Filters.module.scss
  ui/components/Filters/index.js
  ui/components/Search/index.js
  ui/cypress/integration/home.js
  ui/cypress/integration/standards/standard-page.js
  ui/cypress/integration/static-page.js
  ui/cypress/support/commands.js
Labels: bug

#147 [STAN-603] Content updates, homepage Grid
  ui/components/Dataset/index.js
  ui/components/Dataset/style.module.scss
  ui/components/FeedbackFooter/index.js
  ui/components/Flex/style.module.scss
  ui/components/Search/index.js
  ui/package-lock.json
  ui/pages/index.js
  ui/styles/Home.module.scss
Labels: ui changes

#150 [STAN-602] New date format, with tests!
  ui/.eslintrc.js
  ui/components/Analytics/index.js
  ui/components/Dataset/__tests__/dataset.test.js
  ui/components/Dataset/index.js
  ui/components/Filters/index.js
  ui/jest.config.js
  ui/package-lock.json
  ui/package.json
  ui/test/babel.config.js
  ui/test/jest/__mocks__/styleMock.js
  ui/test/jest/setup.js
Labels: enhancement

#158 More accessibility fixes
  ui/components/Dataset/index.js
  ui/components/Filters/Filters.module.scss
  ui/components/Filters/index.js
  ui/components/Form/CheckboxGroup.js
  ui/components/Layout/index.js
  ui/components/Search/index.js
  ui/components/Select/index.js
Labels: enhancement, accessibility change

#159 [STAN-631] simplify markdown rendering
  ui/components/MarkdownBlock/index.js
  ui/package.json
  ui/pages/[page].js
Labels: enhancement, accessibility change

#160 [STAN-519] simplify search button style states
  ui/components/Search/style.module.scss
Labels: enhancement, accessibility change
